config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  
 
  devise_for :users
  #resources :orders, only: [:new, :create]
  resources :items
  resource :cart, only: [:show] do
    post 'add_item/:item_id', to: 'carts#add_item', as: 'add_item'
    delete 'remove_item/:id', to: 'carts#remove_item', as: 'remove_item'
   
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :galeries, only: [:index]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "items#index"
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

get 'about', to: 'pages#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :cart_items, dependent: :destroy
  
  
  validates :title, presence: true 
  validates :image_url, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy

   # Validation pour les champs ajoutés
   validates :name, presence: true
  after_create :create_cart, :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  private

  def create_cart
    Cart.create(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permettre le paramètre :name pour l'inscription et la mise à jour du compte
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user! 

  def add_item
    user = current_user
    item = Item.find_by(id: params[:item_id])

    if item
      cart = user.cart || user.create_cart
      if cart.items.include?(item)
        flash[:alert] = "#{item.title} est déjà dans votre panier."
      else
        cart.items << item
        flash[:notice] = "#{item.title} a été ajouté à votre panier."
      end
    else
      flash[:alert] = "L'article que vous essayez d'ajouter n'existe pas."
    end

    redirect_to cart_path(cart)
  end
  
  def show
    @cart = current_user.cart
    if @cart
      @items = @cart.items
    else
      flash[:alert] = "Votre panier est vide."
      redirect_to root_path
    end
  end
  

  # def remove_item
  #   @cart = current_user.cart
  #   item = @cart.items.find(params[:id])
  #   @cart.items.delete(item)

  #   flash[:notice] = "L'article a été retiré du panier."
  #   redirect_to cart_path
  # end

  def remove_item
    @cart = current_user.cart
  
    # Recherche sécurisée de l'article
    item = @cart.items.find_by(id: params[:id])
    if item
      @cart.items.delete(item) # Utilise destroy si nécessaire : item.destroy
      flash[:notice] = "L'article a été retiré du panier."
    else
      flash[:alert] = "L'article n'existe pas ou n'est pas dans votre panier."
    end
  
    redirect_to cart_path
  end
  

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    Stripe.api_key = ENV['SECRET_KEY']



    @total = params[:total].to_d
    @event_id = params[:event_id]
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
        metadata: {
          event_id: @event_id
        },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url + '?session_id={CHECKOUT_SESSION_ID}',
      metadata: { event_id: @event_id }
    )
    redirect_to @session.url, allow_other_host: true
    
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    
  end

  def cancel
    redirect_to root_path, alert: "Paiement annulé."
  end
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController

  def index
    @items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_path, status: :see_other, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end
    
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new

  end

  def create
    # Before the rescue, at the beginning of the method
@stripe_amount = 500
begin
  customer = Stripe::Customer.create({
  email: params[:stripeEmail],
  source: params[:stripeToken],
  })
  charge = Stripe::Charge.create({
  customer: customer.id,
  amount: @stripe_amount,
  description: "Achat d'un produit",
  currency: 'eur',
  })
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_order_path
end
# After the rescue, if the payment succeeded
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carts/show.html.erb
<div class="container mt-5">

  <h1>Votre Panier</h1>

  <% if @items.any? %>
  <ul>
    <% @items.each do |item| %>
    <li>
      <strong><%= item.title %></strong> - <%= number_to_currency(item.price) %>
      <%= button_to 'Retirer', remove_item_cart_path(item), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: "btn btn-outline-danger" %>
    </li>
    <% end %>
  </ul>

  <p>
    Total : <%= number_to_currency(@items.sum(&:price)) %>
  </p>
  <% else %>
  <p>Votre panier est vide.</p>
  <% end %>
  <%= button_to "Passer commande", checkout_create_path(total: @items.sum(&:price)), class: "btn btn-success", data: { turbo: false } %>
  <%= link_to 'Continuer vos achats', items_path %>

app/views/checkout/cancel.html.erb
<div class="container text-center my-5">
  <h1>Echec</h1>
  <p>Le paiement n'a pas abouti.</p>
</div>

app/views/checkout/create.html.erb
<h1>Checkout#create</h1>
<p>Find me in app/views/checkout/create.html.erb</p>

app/views/checkout/success.html.erb
<div class="container text-center my-5">
  <h1>Succès</h1>
  <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p>
  <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p>
</div>

app/views/galeries/index.html.erb
<h1 class="text-center" style="margin: 20px;">Liste des chatons</h1>
</div>
<div class="container">
  <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @items.each_with_index do |item, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
        <img src="<%= item.image_url %>" class="d-block w-100" alt="<%= item.title %>">
        <div class="carousel-caption d-none d-md-block">
          <h5><%= item.title %></h5>
          <p><%= item.description %></p>
          <p><%= number_to_currency(item.price) %></p>
        </div>
      </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="show.css">
    <title>Card</title>
</head>
<body>

<div id="<%= dom_id item %>">
  <div class="item-title">
    <p>
      <strong>Title:</strong>
      <%= item.title %>
    </p>
  </div>

  <div class="item-description">
    <p>
      <strong>Description:</strong>
      <%= item.description %>
    </p>
  </div>

  <div class="item-price">
    <p>
      <strong>Price:</strong>
      <%= item.price %>
    </p>
  </div>

  <div class="item-image-url">
    <p>
      <strong>Image url:</strong>
      <%= item.image_url %>
    </p>
  </div>
</div>

app/views/items/edit.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="show.css">
    <title>Card</title>
</head>
<body>

<% content_for :title, "Editing item" %>

<div class="header">
  <h1>Editing item</h1>
</div>

<div class="form-container">
  <%= render "form", item: @item %>
</div>

<div class="actions">
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="show.css">
  <title>Card</title>
</head>

<body>

  <div class="banner">
    <div class="banner-content">
      <%= image_tag "Sketches_3.png", alt: "Banner Image", class: "banner-img" %>
      <h2>Bienvenue sur notre site des chatons !</h2>
    </div>
  </div>


  <p style="color: green"><%= notice %></p>

  <div class="title">
    <h1>Liste des chatons</h1>
  </div>

  <div class="container">
    <div class="row">
      <% @items.each do |item| %>


      <div class="col-md-3 mb-4">
        <div class="card">
          <img src="<%= item.image_url %>" class="card-img-top" alt="<%= item.title %>">
          <div class="card-body">
            <h5 class="card-title"><%= item.title %></h5>
            <p class="card-text"><%= item.description %></p>
            <p><%= number_to_currency(item.price) %></p>
          </div>
          <div class="card-footer">
            <%= link_to "Voir le produit", item, class: "btn btn-primary" %>
          </div>
        </div>
      </div>

      <% end %>
    </div>

    <div class="new-item-link">
      <%= link_to "New item", new_item_path %>
    </div>

app/views/items/new.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="new.css">
    <title>Card</title>
</head>
<body>

<% content_for :title, "New item" %>

<div class="header">
  <h1>New item</h1>
</div>

<div class="form-container">
  <%= render "form", item: @item %>
</div>

<div class="back-link">
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<%= stylesheet_link_tag 'items/show', media: 'all' %>

<div class="notice">
  <p style="color: green"><%= notice %></p>
</div>

<div class="product-details">
  <div class="product-left">
    <img src="<%= @item.image_url %>" alt="<%= @item.title %>" class="product-image img-fluid mb-3">
  </div>

  <!-- Section droite : description et boutons -->
  <div class="product-right">
  <h1 class="product-title"><%= @item.title %></h1>
    <p class="product-description"><%= @item.description %></p>
    <p class="product-price"><%= number_to_currency(@item.price) %></p>

<div class="actions">
  <%= button_to "Add to Cart", add_item_cart_path(@item), method: :post, class: "btn btn-primary add-to-cart-btn" %>

  <%= link_to "Back to items", items_path %>
</div>


</div>

<%#button_to "Destroy this item", @item, method: :delete %>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Footer</title>
</head>
<body>

<div class="footer">
<div class="footer-container">
    <!-- Logo et nom -->
    <div class="footer-content">
        <%= image_tag "Vector.png", alt: "Logo", class: "footer-logo" %>
        <div class="footer-text">
        <h1>Chatographe</h1>
        <p>Les plus belles photos de chatons</p>
    </div>
</div>
    <!-- Colonnes de contenu -->
    <div class="footer-column">
        <h3>Découvrez</h3>
        <ul>
            <li><a href="#">Editions limitées</a></li>
            <li><a href="#">Produits favoris</a></li>
            <li><a href="#">Catégories</a></li>
            <li><a href="#">Promotions</a></li>
        </ul>
    </div>
    <div class="footer-column">
        <h3>A propos</h3>
        <ul>
            <li><a href="#">Produits</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms & Conditions</a></li>
        </ul>
    </div>
    <div class="footer-column">
        <h3>Info</h3>
        <ul>
            <li><a href="#">Chatographe@gmail.com</a></li>
            <li><a href="#">01 23 45 56 78</a></li>
            <li><a href="#">Contatez-nous</a></li>
        </ul>
    </div>
</div>

<!-- Copyright -->
<div class="footer-copyright">
    <p>© 2024 Chatographe. Tous droits réservés.</p>
    <p>Designed by Zaineb, Steph, Shirley et Nora</p>
</div>
</div>   
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= content_for(:title) || "Chatographe Project" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>


  <link rel="manifest" href="/manifest.json">
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link href="https://unpkg.com/bootswatch@5.3.2/dist/flatly/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>


  <%= yield :head %>


  <link rel="manifest" href="/manifest.json">
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">



  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Logo ou Nom de l'application -->
      <%= image_tag "Vector.png", alt: "logo", class: "navbar-logo" %>
      <%= link_to "Chatographe", root_path, class: "navbar-brand" %>


      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to "Galerie", galeries_path, class: "btn btn-outline-primary me-2"%>
          </li>

          <li class="nav-item">
            <%= link_to 'À propos', about_path, class: 'btn btn-primary' %>
          </li>

          <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Modifier mon profil", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mon Panier', cart_path, class: 'btn btn-primary' %>
          </li>
          <% else %>

          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "btn btn-outline-primary me-2" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="content">
    <%= yield %>
    <script src="https://js.stripe.com/v3/"></script>
  </div>
  <%= render 'layouts/footer' %>


</body>


</html>

app/views/orders/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<%= form_tag orders_path do %>
<article>
  <% if flash[:error].present? %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
  <% end %>
  <label class="amount">
    <span>Amount: $5.00</span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Achat d'un produit" data-amount="500" data-locale="auto">
</script>
<% end %>

app/views/pages/about.html.erb
<h1>À propos de nous</h1>
<p>Nous sommes une équipe passionnée, dédiée à offrir le meilleur service...</p>

<!-- Conteneur des cartes -->
<div class="container mt-4">
  <div class="row">
    <!-- Première carte -->
    <div class="col-md-4">
      <div class="card">
       <%= image_tag 'Capture d’écran 2024-11-28 205529.png', class: 'card-img-top', alt: 'Photo de l\'équipe 1' %>
        <div class="card-body">
          <h5 class="card-title">Zaineb</h5>
          <p class="card-text">Une brève description de la personne ou de l'activité. Elle est passionnée par...</p>
        </div>
      </div>
    </div>

    <!-- Deuxième carte -->
    <div class="col-md-4">
      <div class="card">
        <%= image_tag 'Capture d’écran 2024-11-28 205549.png', class: 'card-img-top', alt: 'Photo de l\'équipe 2' %>
        <div class="card-body">
          <h5 class="card-title">Nora</h5>
          <p class="card-text">Une brève description de la personne ou de l'activité. Elle est spécialisée dans...</p>
        </div>
      </div>
    </div>

    <!-- Troisième carte -->
    <div class="col-md-4">
      <div class="card">
       <%= image_tag 'Capture d’écran 2024-11-28 205608.png', class: 'card-img-top', alt: 'Photo de l\'équipe 2' %>
        <div class="card-body">
          <h5 class="card-title">Stephan</h5>
          <p class="card-text">Une brève description de la personne ou de l'activité. Il aime travailler sur...</p>
        </div>
      </div>
    </div>
  </div>
</div>